#!/bin/bash

#Global Variables

BTRFS_MOUNT=/tmp/subs
ROOT_PART=/dev/vda3

#Functions

create_mountpoint(){
    if [[ ! -d "$BTRFS_MOUNT" ]]; then
    echo "Creating folder \"$BTRFS_MOUNT\""
    mkdir "$BTRFS_MOUNT"
fi
}

rollback() {
    #Variables
    local PROFILE="$1"
    local HOME_FOLDER=/home/"$PROFILE"
    create_mountpoint
    mount "$ROOT_PART" "$BTRFS_MOUNT"
    LATEST=$(stat -c '%y %n' "$BTRFS_MOUNT"/@snapshots/"$1"/* | sort -n -r | head -n 1 | cut -f 4 -d " ")
    # echo "$LATEST"
    umount "$HOME_FOLDER"
    echo "@$PROFILE"
    btrfs subvolume delete -c "$BTRFS_MOUNT"/@"$1"
    btrfs subvolume snapshot "$LATEST" "$BTRFS_MOUNT"/@"$1"
    umount "$ROOT_PART"
    mount "$HOME_FOLDER"
}

#Determine which function the user passed in to the command

case "$1" in
"") ;;
rollback)
    "$@"
    exit
    ;;
*)
    echo "Unknown function: $1"
    exit 2
    ;;
esac
