#!/bin/bash

#Global Variables

BTRFS_MOUNT=/root/toplevel

#Functions

rollback() {
    local PROFILE="$1"
    local HOME_FOLDER=/home/"$PROFILE"
    local LATEST

    if dirs=("$BTRFS_MOUNT"/@snapshots/"$PROFILE"/*/) && [[ -d ${dirs[0]} ]]; then
        LATEST=$(stat -c '%y %n' "$BTRFS_MOUNT"/@snapshots/"$1"/* | sort -n -r | head -n 1 | cut -f 4 -d " ")
        printf 'Snapshots exist for %s.\nBeginning rollback to latest snapshot at %s\n' "$PROFILE" "$LATEST"
        umount "$HOME_FOLDER"
        btrfs subvolume delete -c "$BTRFS_MOUNT"/@"$PROFILE"
        btrfs subvolume snapshot "$LATEST" "$BTRFS_MOUNT"/@"$PROFILE"
        mount "$HOME_FOLDER"
    else
        echo "No snapshots exist for '$PROFILE'"
        exit 2
    fi
}

make() { #create a new profile revertable profile
    local PROFILE="$1"
    local HOME_FOLDER=/home/"$PROFILE"

    #create user w/o home folder (will be created manually later)
    useradd -M -s /bin/bash "$PROFILE"
    #set password
    passwd "$PROFILE"
    #create subvolume
    btrfs subvolume create /root/toplevel/@"$PROFILE"
    #create entry in fstab
    ROOT_LINE=$(grep subvol=@" " /etc/fstab)
    TEMP_ENTRY=${ROOT_LINE//subvol=@/subvol=@"$PROFILE"}
    NEW_ENTRY=${TEMP_ENTRY/\//\/home/"$PROFILE"}
    echo "$NEW_ENTRY"
    #TODO:  Insert "NEW_ENTRY" into fstab
    #make home folder
    mkdir /home/"$PROFILE"
    chown "$PROFILE":"$PROFILE" /home/"$PROFILE"   
    #mount btrfs subvolume
    #Propulate the home folder with default files and folders
    su -c "cp -r /etc/skel/. /home/$PROFILE" "$PROFILE"
    su -c xdg-user-dirs-update "$PROFILE"
    #create folder in /.snapshots
    #take initial snapshot

    echo "hello world"
}

#Determine which function the user passed in to the command

case "$1" in
"") ;;
rollback)
    "$@"
    exit
    ;;
make)
    "$@"
    exit
    ;;
*)
    echo "Unknown function: $1"
    exit 2
    ;;
esac
