#!/bin/bash

# check for root user
if [[ $EUID -ne 0 ]]; then
        echo "This installer must be run by user with admin privleges" 1>&2
        exit 1
fi

# Install files

install -v -m 0644 -o root -g root etc/systemd/system/justso@.service -t /etc/systemd/system/
install -v -m 0700 -o root -g root usr/local/sbin/justso /usr/local/sbin/

# Reload systemd daemon

systemctl daemon-reload