#!/bin/bash

#Global Variables

BTRFS_MOUNT=/root/toplevel
SNAPS="$BTRFS_MOUNT"/@snapshots
MNT_OPTS="rw,noatime,compress=zstd:1,space_cache=v2"

#Functions

back() {
    local PROFILE="$1"
    local HOME_FOLDER=/home/"$PROFILE"
    local LATEST

    mount -o "$MNT_OPTS" /dev/vda3 "$BTRFS_MOUNT"

    if dirs=("$BTRFS_MOUNT"/@snapshots/"$PROFILE"/*/) && [[ -d ${dirs[0]} ]]; then
        LATEST=$(stat -c '%y %n' "$BTRFS_MOUNT"/@snapshots/"$1"/* | sort -n -r | head -n 1 | cut -f 4 -d " ")
        printf 'Snapshots exist for %s.\nBeginning rollback to latest snapshot at %s\n' "$PROFILE" "$LATEST"
        umount "$HOME_FOLDER"
        btrfs subvolume delete -c "$BTRFS_MOUNT"/@"$PROFILE"
        btrfs subvolume snapshot "$LATEST" "$BTRFS_MOUNT"/@"$PROFILE"
        mount "$HOME_FOLDER"
        umount "$BTRFS_MOUNT"
    else
        echo "No snapshots exist for '$PROFILE'"
        umount "$BTRFS_MOUNT"
        exit 2
    fi
}

make() { #create a new profile revertable profile
    local PROFILE="$1"
    local HOME_FOLDER=/home/"$PROFILE"
    local NOW
    NOW=$(date --iso-8601=seconds)

    #If fstab backup folder doesn't exist, create it
    if [ ! -d /root/fstab_backup ]; then
        mkdir /root/fstab_backup
    fi

    #create user w/o home folder (will be created manually later)
    useradd -M -s /bin/bash "$PROFILE"
    #set password
    passwd "$PROFILE"
    #mount toplevel
    mount -o "$MNT_OPTS" /dev/vda3 "$BTRFS_MOUNT"
    #create subvolume
    btrfs subvolume create "${BTRFS_MOUNT}/@${PROFILE}"
    #create entry in fstab
    ROOT_LINE=$(grep subvol=@" " /etc/fstab)
    TEMP_ENTRY=${ROOT_LINE//subvol=@/subvol=@"$PROFILE"}
    NEW_ENTRY=${TEMP_ENTRY/\//\/home/"$PROFILE"}
    echo "$NEW_ENTRY"
    #Create a backup of fstab
    cp -a /etc/fstab /root/fstab_backup/fstab."${NOW}".bak
    #Insert "NEW_ENTRY" into fstab
    sed --in-place=.bak "/^.*\/home.*/a $NEW_ENTRY" /etc/fstab
    #make home folder
    mkdir "$HOME_FOLDER"
    #mount btrfs subvolume and set ownership
    mount "$HOME_FOLDER"
    chown "$PROFILE":"$PROFILE" /home/"$PROFILE"
    #Propulate the home folder with default files and folders
    su -c "cp -r /etc/skel/. /home/$PROFILE" "$PROFILE"
    su -c xdg-user-dirs-update "$PROFILE"
    #create folder in /.snapshots
    if [ ! -d "${SNAPS}/${PROFILE}" ]; then
        mkdir "${SNAPS}/${PROFILE}"
    fi
    #take initial snapshot
    btrfs subvolume snapshot -r "$HOME_FOLDER" "${SNAPS}/${PROFILE}/${PROFILE}-${NOW}"

    #unmount toplevel
    umount "$BTRFS_MOUNT"

    
}

#Determine which function the user passed in to the command

case "$1" in
"") ;;
back)
    "$@"
    exit
    ;;
make)
    "$@"
    exit
    ;;
*)
    echo "Unknown function: $1"
    exit 2
    ;;
esac
